### ISSUE TITLE
No feed back on tool bar after click funtion has been run

### ISSUE THREAD

**Issue by hornoo** [OtagoPolytechnic/OpenSourceWindowsGazeControl#3]
**Trigger**
Selecting any function on the gaze tool bar via gazing at a function button.

**Desired Behavior**
Select a button on the gaze tool bar, the selected item\button changes and appears selected compared with the other buttons, Once the selected function has completed or timed out, the tool bars appearance goes back to appearing that no buttons\items are selected, Feed back about a function complementing successfully eg green flash and for failure\timeout red flash .

 **Observed behavior**
When an button is selected it appears to still look selected(changes colour and stays that colour), until another button is selected, even if a large amount of time has or the selected function has completed

**Comment by hornoo** [comment]
Implemented functionality that now resets button colors to default after a mouse action is run.

**Comment by LJMoffitt** [comment]
Hornoo m8, what's going on here? Sort it mate

**Comment by hornoo** [comment]
[image: Inline image 1]I think you need to unsubscribe
